### ISSUE TITLE
trtl hard fork

### ISSUE THREAD

**Issue by eddiewang927** [xmrig/xmrig#1028]
Trtlcoin network will upgrade after 14days
Does xmrig and xmrig-proxy support new trtl  algorithm?

**Comment by Desmond168** [comment]
The TRTL is one of the large Altcoin, please support this timely. It's very appreciated.

**Comment by eddiewang927** [comment]
In the past few days, we managed compile and test the TRTLrig for the Argon2id Chukwa algo which TurtleCoin will fork to at block 1,800,000.

https://medium.com/@turtlecoin/this-week-in-turtlecoin-may-28-2019-90f5051eb932
https://blog.turtlecoin.lol/archives/the-quest-for-decentralized-proof-of-work/

**Comment by eddiewang927** [comment]
https://github.com/turtlecoin/trtlrig/tree/add_chukwa

**Comment by 2010phenix** [comment]
@eddiewang927 why you want add to cryptonight miner something from another custom "song" ....

**Comment by Desmond168** [comment]
I thought, Eddiewang want to provide more reference for miner revision.

**Comment by Nakamoto-san** [comment]
+1

**Comment by Spudz76** [comment]
If trtl people forked this miner to hack in new algos (as seen on trtlrig), they should submit changes back upstream rather than endlessly hack on some deadended fork that no longer compares to current upstream code (if not now, in the future it will be outdated).

**Comment by asylum119** [comment]
I would like this algo to be added as I mine turtle with xmrig but at the same time I feel that a projects algo change with no pull request should not be continually rewarded to any project. Turtlecoin encourages pull requests for its project so this behaviour should carry on to mining software. 

Algo support should be a considered part of the core project rather than Meh, the community and mining software will figure it out and maybe add GPU support at some stage.... Hold my beer while I change to another algo for an even more inflated hash rate.

You will have to forgive my negativity but its been brewing for a bit

**Comment by bobbieltd** [comment]
I agree with asylum119. I think Turtlecoin devs will pull request in appropriate time (they need to make tests before doing it)
