### ISSUE TITLE
witch one?

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig#1043]
https://github.com/wownero/RandomWOW
OR
https://github.com/tevador/RandomX/

**Comment by xmrig** [comment]
For Wownero is RandomWOW, but technically miner can work with reference RandomX implementation, it useless, but possible, because both libs use same C interface, but in future RandomX source will be included into miner source in some way, because right now announced 3 RandomX variants, 1 live (Wownero) an 2 in future (Monero and Loki).
Thank you.
