### ISSUE TITLE
Unifiqued DLL Cuda 

### ISSUE THREAD

**Issue by LearnMiner** [xmrig/xmrig#1302]
How can I put all in same exe? without dll

**Comment by xmrig** [comment]
There 2 types of dll:
1. `xmrig-cuda.dll` itself, technically possible make it static, it has some restrictions for example not possible use gcc, because CUDA not support this compiler on Windows, it require write some code anyway, right now it not possible. 
2. NVRTC libraries, for example `nvrtc64_101_0.dll` and `nvrtc-builtins64_101.dll`, only way to avoid these dlls is remove algorithms where it used, for example `cn/r` and it also require write some code.

Thank you.
