### ISSUE TITLE
xmrig 5.5.0 periodical "Rejected share: invalid result"

### ISSUE THREAD

**Issue by chelmedvedosvin** [xmrig/xmrig#1491]
I have 64 rigs running on ubuntu with Intel(R) Celeron(R) CPU G3930 @ 2.90GHz and G3900
and 4 from them are producing such error (others work fine).
Screenshot: http://prntscr.com/qktr35
So pool ban my ip because of bad shares. How can I fix this trouble?

**Comment by miner91** [comment]
> So pool ban my ip because of bad shares.
First off, don't use pools that bans your whole network because of couple invalid shares like supporxmr, it's stupid. I talked in the past with admin of supportxmr (m5m400), he told he will turn this off but didn't even increase the limit after which you will get temporarily banned. I use supportxmr for couple years and never had a problem, I get couple invalids per day so it's not a big deal but I don't want my whole network to be off because of that for X minutes.

Use minerxmr pool.

Second, check temps, memory, use xmrig with debugging flag compiled and check the logs.

**Comment by chelmedvedosvin** [comment]
I have created topology xml:
http://prntscr.com/qlrdqk
