### ISSUE TITLE
XMRig with Intel Xeon e5-1680 v2 L2 and L3 cache

### ISSUE THREAD

**Issue by ValoWaking** [xmrig/xmrig#1499]
I want to ask. If CPU have L2 2MB cache XMRig will use for mining L2 and L3 cache?
In the issue Intel Xeon e5-1680 v2 has 13 (L2 - 2MB, L3 - 25MB cache) possible threads for mining?

**Comment by ValoWaking** [comment]
the question is - can L2 and L3 cache work together and used by XMRig?

**Comment by kio3i0j9024vkoenio** [comment]
For each thread you need 2MB L3 Cache and 256KB L2 Cache. Note that you need BOTH to be satisfied for each thread.

The Xeon e5-1680 v2 has:

http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5-1680%20v2.html

The number of CPU cores: 8
The number of threads: 16
Level 2 cache size: 8 x 256 KB 8-way set associative caches
Level 3 cache size: 25 MB 20-way set associative shared cache

For mining you can only use the 8 real cores (not the HT cores) because of the L2 limit of Level 2 cache size: 8 x 256 KB

**Comment by ValoWaking** [comment]
ok, thanks! What about ryzen 3700, he can run with 16 threads? 

Level 2 cache size 8 x 512 KB 8-way set associative unified cache
Level 3 cache size | 32 MB 16-way set associative shared cache

**Comment by xmrig** [comment]
Ryzen 3700 hash enough cache for 16 threads.
Thank you.
