### ISSUE TITLE
Xmrig bus error arm galaxy s5

### ISSUE THREAD

**Issue by Izder456** [xmrig/xmrig#1514]
I get a bus error on my galaxy s5 {see screenshot} 
![Screenshot_20200124-054851](https://user-images.githubusercontent.com/16585414/73067094-595f5a00-3e6d-11ea-870d-2ce6c71ef3b3.png)

**Comment by Spudz76** [comment]
Not enough memory.  RandomX requires 2080MB (that's 2GB + 32MB) and the Galaxy S5 has 2GB total.  Need 4GB devices minimum for RandomX.  The only bug is it should have exited rather than trying the "slow" mode (which also has not enough memory).

It should mine other algos that aren't RandomX based...
