### ISSUE TITLE
How can I change which core to mine?

### ISSUE THREAD

**Issue by IAMPARKSANG** [xmrig/xmrig#1625]
![image](https://user-images.githubusercontent.com/48522014/77840794-2a939600-71c6-11ea-8582-7d498abfea01.png)

I am mining with 5 cores, and other one core is doing web surfing or else with .  I've set my cpu to use only 5 cores for mining and I am worried about cpu0,1,2,3,4 working too much. 
How can I choose which core to work? I want 1,2,3,4,5 to mine and cpu0 to do other things

**Comment by setuidroot** [comment]
You'd do this by setting the CPU thread affinity... it's easier just to show you.  Can you post your current config.json file?

If you do so, I will modify it to set affinity to the CPU threads you want it to mine on.

Otherwise, just read here about thread affinity: https://github.com/xmrig/xmrig/blob/dev/doc/CPU.md

Keep in mind that Windows does some funny stuff with threads so you may have to affine to all odd or all even cores to get the outcome you want.
