### ISSUE TITLE
what's going on, falling hash?

### ISSUE THREAD

**Issue by klesilva** [xmrig/xmrig#1649]
I'm mining normally, after 1 hour drastically drops the hash, when devfee hash starts back to normal, as soon as it ends it falls again and does not return to normal. Windows 10 Pro, R73800X 32GB DDR4 3600Mhz, CPU usage is normal. before I was using the R72700X and that didn't happen.

![Capturar](https://user-images.githubusercontent.com/40640747/79685971-06e6cd00-8213-11ea-8b92-c34f9830c88f.PNG)

**Comment by trasherdk** [comment]
Looks like you are mining `cn/r`.

**Comment by xmrig** [comment]
Nicehash doesn't support algorithm negotiation, so you must specify `algo` option and must not use `coin` option, configuration should looks like `"algo": "rx/0", "coin": null,`.

Your current configuration worked fine in the past because only Monero used the `rx/0` algorithm, but now QRL also uses `rx/0` and people use nicehash to mine it. Using the `algo` option is the golden rule for nicehash, you can't control what coin mined.
Thank you.

**Comment by klesilva** [comment]
I understand I will make the modification and see the problem again

**Comment by klesilva** [comment]
@xmrig thanks for the help, more than 2 hours passed the problem did not occur again.
