### ISSUE TITLE
Do we use half of the CPU in mining? Why doesn't he see it all

### ISSUE THREAD

**Issue by restartload** [xmrig/xmrig#1658]
![screenshot_v5_2_0](https://user-images.githubusercontent.com/56207175/80130407-309c4d00-85a1-11ea-9068-a26417f77ae1.png)

**Comment by xmrig** [comment]
This is best configuration for this pair of CPUs, dataset initialization require all threads, mining limited by CPU cache, 256 KB of L2 and 2 MB of L3 per mining thread, since this kind of CPU use non standard cache configuration (large L2) best option is use only physical cores (20), technically this CPU has enough L3 cache for one extra thread per socket, but it useless for this kind of CPU.
Thank you.
