### ISSUE TITLE
Why cpu only uses 50%??????????

### ISSUE THREAD

**Issue by vvring** [xmrig/xmrig#1670]
Why cpu only uses 50%
Large memory support has been turned on
4pcs E7-4850 v3 how to set CPU
4 E7-4850 v3 112 cores only have 55 cores?
How should I set it up?

- 
![1](https://user-images.githubusercontent.com/47848167/81072480-c8425980-8f18-11ea-80d4-d9ee5cc16c66.PNG)
![2](https://user-images.githubusercontent.com/47848167/81072490-cb3d4a00-8f18-11ea-91a0-07797d97e902.PNG)
![3](https://user-images.githubusercontent.com/47848167/81072494-cc6e7700-8f18-11ea-888d-b3ffa04e2051.PNG)

**Comment by Masterbob79** [comment]
"Yield": false might help

**Comment by Miner9009** [comment]
Cache requirements dude, 2MB per thread.

**Comment by divinity76** [comment]
wrong, you don't have 112 cores, you have 56 cores. 
thanks to hyperthreading, they look like 112 cores to the OS, but 50% of those cores are hyperthreaded virtual cores, and if you actually try to mine on the real core, and the hyperthreaded core simultaneously, your overall hashrate will actually go SLOWER than just mining on the real cores.

hence, xmrig actively avoids mining on the hyperthreaded cores, which seems, to the OS, like it's only mining on 50% of your cores (because the hyperthreaded cores are useless for mining)
