### ISSUE TITLE
Hashrate sometimes drops to near 0 while mining RandomX on CPU

### ISSUE THREAD

**Issue by maxime506** [xmrig/xmrig#1721]
Think this has been bugging me for awhile. This happens on either a Ryzen 1st Gen CPU or on a Intel 3rd/4th Gen CPU when mining XMR on XMrig

Even though I have another CMD window to restart miner every 3 hour or so, nonetheless there's a chance that the miner is hashing RandomX at close to 0 (and still load the CPU!) and I will have to restart it to gain full speed. Is there a way the dev can implement a command, such as restart if miner hash at lower than a certain value?

**Comment by downystreet** [comment]
What does your config.json file look like?

**Comment by rawbonesfck** [comment]
I experience something along that line, unsure how to categorize it but usually have 14kh/s but for some reason dropped down to 500h/s then it just stayed at 500 for a while.  i just rebooted because i was in a rush.

**Comment by implodnik** [comment]
This issue is old and probably related to the thread manager in Windows builds 19xx and higher (see #1393, for example). The only more or less reliable way to overcome this I found is to use an external watchdog (in my case it's a simple Powershell script that runs every 10 minutes, checks the 60s hashrate and restarts the process if necessary).

Also, using "-1"s as core number specifiers instead of exact core numbers significantly reduces probability of sudden hashrate drops.

**Comment by xmrig** [comment]
https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
