### ISSUE TITLE
New version hashrate drop

### ISSUE THREAD

**Issue by niko1094** [xmrig/xmrig#19]
Hi. 
In 0.8.2 version, I had an avg of 236 h/s. Now with 1.0.1-msvc-win64 version, I have an avg of 230 h/s and with 1.0.1-gcc-win64 version I have an avg of 234.4 h/s.

I have windows 10 x64 and i5-3570.

Anyway, thank you very much: D

**Comment by xmrig** [comment]
Old version calc 60 hashes at one single loop, this solution has old history, but not so good for slow hashes like cryptonight, because if new job received, miner not immediately stop previous job.

In new version this situation impossibility, outdated job newer be mined. But these checks can costs few H/s.

Of course I will try any way to increase hashrate in future.
Thank you.

**Comment by niko1094** [comment]
Ah, okay. No problem.
One more question, you recommend msvc version for win64. Do you know why I have less hashes than with the gcc version?

**Comment by xmrig** [comment]
In my tests and user feedback msvc little bit faster. But difference is very small, so there 2 versions.
I remove this recommendation.

Maybe gcc version better for your CPU, maybe some background tasks reduce performance.

**Comment by niko1094** [comment]
Okay :D
Very thanks you for your work and your attention.
