### ISSUE TITLE
Kawpow memory issue...

### ISSUE THREAD

**Issue by berghemhack** [xmrig/xmrig#1962]
...

**Comment by Spudz76** [comment]
Would imagine the slower family card is goofing up the loop timing.  Is it stable with the 4GB Baffin disabled and just the three of the same 8GB card?

**Comment by M4shy** [comment]
This issue seems closed... ok. Don't blame me but I didn't want to open another ticket in this case. 
So I'm still having this kind of problem with my GTX 780 (3GB) and setted my virtual memory like : GPU mem size * number of GPU.  Am i right ?

Here the logs,
KawPow light cache for epoch 215 calculated (8488ms)
KawPow failed to initialize DAG: <kawpow_prepare>:62 "out of memory"

Anyone ?

**Comment by SChernykh** [comment]
@M4shy KawPow DAG size is 2.7 GB now, it's not enough memory on a 3 GB card if you're running Windows 10. Try Windows 7 or Linux, they leave more GPU memory available for mining.
