### ISSUE TITLE
Probably not a "Bug" per se, but this really bugs me.....

### ISSUE THREAD

**Issue by fwet** [xmrig/xmrig#2072]
Click the "Build from Source" link on certain public wireless nets using Cisco Umbrella nanny software, and you will be redirected to a page telling you xmrig.com is malware
![Screenshot from 2021-01-30 17-19-34](https://user-images.githubusercontent.com/76499781/106369471-bc58bc00-631f-11eb-8dfe-807504437309.png)

Going to assume this is politically motivated and not actual malware, but I figured I would mention it

**Comment by toynn** [comment]
Hi - I think this is pretty typical for any mining software, not just xmrig. Unfortunately there are cases where someone takes the mining software code and includes it in a bot to spread onto unsuspecting users. So downloading with Chrome or Firefox will be block as possible virus and most virus scanners flag crypto mining software as malware. On my computer I always need to click the "allow access/not a virus" or what ever you need to do so that the mining software is allowed.

**Comment by Spudz76** [comment]
Yep, nothing we can do about that.  Identical to getting socially cancelled on networks, based upon whims, with no path to reverse.

**Comment by fwet** [comment]
> Unfortunately there are cases where someone takes the mining software code and includes it in a bot 

Guilt by association then. Cisco umbrella censors plenty of other content for ideological reasons, not just security.    Malware researchers should remove false positive results like this, or disclose what malware is on the xmrig site so it can be fixed. Otherwise it should be fairly obvious they have ulterior motives.

**Comment by Spudz76** [comment]
Definitely not just Cisco.  ISPs are now black-holing DNS records for known mining sites.  Some are slapping closed any connection to any port with any protocol (SSL or not) to known mining IPs.

Essentially if you intend to mine on purpose you should be smart enough to get around the issues they have created to protect the majority part of society (most people, who don't even know what mining is).
