### ISSUE TITLE
Unable to increase number of threads

### ISSUE THREAD

**Issue by aliiqbal1984** [xmrig/xmrig#2084]
Hi I am having 20 core server with 60Mb L3 cache running the xmrig by default config file I get 20 core and 20 threads 

Can someone help how I can increase threads to 30 what changes will be needed in config file ? Please help.

**Comment by Spudz76** [comment]
fake cores do not help rate, only real cores
you have 20 real cores?

what algorithm?

Run CN-Heavy and it will stop using all cores, but jam all cache full (60MB / 4MB scratchpad = 15 cores).
To fit that CPU model ideally you would need an algo with 3MB scratchpads, which do not exist).

**Comment by Lonnegan** [comment]
Haven should work perfectly on your CPU.

**Comment by aliiqbal1984** [comment]
> fake cores do not help rate, only real cores
> you have 20 real cores?
> 
> what algorithm?
> 
> Run CN-Heavy and it will stop using all cores, but jam all cache full (60MB / 4MB scratchpad = 15 cores).
> To fit that CPU model ideally you would need an algo with 3MB scratchpads, which do not exist.

Thanks for your response, I got UCSC server where I am trying it have total 24 CPUs x 2.294 GHz

Processor type Intel Xeon ES-2670 v3 having 2 sockets 12 real cores on each socket

I am actually looking for suggestion on what to add in my config file to start running more threads  what will be the best way to get most out of this CPU.

**Comment by Lonnegan** [comment]
If you want to use more threads manually, you have to edit config.json, section "cpu", line "rx". There you can set which cores of your CPU should be used for Monero mining.

**Comment by Spudz76** [comment]
Depends on algo because they all have different sizing and saturation requirements.

For generic Cryptonight at 2MB scratchpad size you can run 12 threads per socket (24 threads total) and you will have 6MB of unused cache per socket (12MB unused total).  Because you've run out of real cores before running out of cache.

For Cryptonight-Heavy at 4MB scratchpad size you can run 7 threads per socket (14 threads total) because that's maximum of cache each has (30MB/4MB = 7.5 but you can't have half a thread so, 7).  This leaves 5 cores and 2MB of cache per socket unused.  BUT it might be more profitable than whatever other algo that "uses more of the cpu" or fits better.

For other algos it gets a bit more complicated, and they begin using system ram instead of just cache and cores.

**Comment by bezatine** [comment]
I seen alot of the custom stuff for different algorithms here and google search xmrig max threads or max cpu usage, I feel like users are saying an extra 20-22% on different algo but they have some benchmark tweaks you can look up too, its something about the wrmsr or rdsmr line can tweaked for extra 2% or it can lower, but yea I found a lot in the command line options page on how you can push it

https://xmrig.com/docs/miner/command-line-options
