### ISSUE TITLE
How can I set the exact number of threads to use for RandomX in JSON config?

### ISSUE THREAD

**Issue by crocket** [xmrig/xmrig#2107]
On command line, I can specify `-t` or `--threads`.
In JSON config, there is https://github.com/xmrig/xmrig/blob/master/doc/CPU.md#threads-definition and https://github.com/xmrig/xmrig/blob/master/doc/CPU.md#max-threads-hint-since-v420

Because my CPU has 12 threads, max-threads-hint cannot exactly specify number of threads to use.
10/12 = 0.8333333.....

Short object format for "threads" is not well defined, either. What is `intensity`? What are real valid values for CPU affinity? What is CPU affinity? What does each value of CPU affinity do?

Why can I not just specify `threads: 8` in JSON config?

https://github.com/xmrig/xmrig/blob/master/src/config.json doesn't really tell me how threads are manipulated.

Where am I supposed to define `"threads"` in JSON config?

Thread configuration should be unambiguously documented.

**Comment by Lonnegan** [comment]
https://github.com/xmrig/xmrig/issues/2084#issuecomment-774500529

**Comment by crocket** [comment]
The real issue is amgibuity of documentation.

I finally understood https://github.com/xmrig/xmrig/blob/master/doc/CPU.md after watching xmrig automatically write configuration and wagching xmrig output on terminal emulator for hours.

However, https://github.com/xmrig/xmrig/blob/master/doc/CPU.md doesn't explain profile clearly. CPU.md implicitly assumes that I already know what profile is. That's why I was confused.

CPU.md also doesn't explain that each profile is a thread configuration for any algorithm that matches the profile. That's why I was confused to hell.

**Comment by Spudz76** [comment]
I'm a computer veteran and didn't need the documentation to figure out how it works.  Having looked at it for the first time now, it could be improved.

I'm actually more confused about what you're confused about.

Hints are used during autoconfiguration and are completely ignored after that phase.  That's why they are hints.  If you have 80 threads hand-configured in a definition it's not going to stop that, because it's a hint not a limit.  Conversely if you supply a hint of 80 threads but your CPU only has enough cores or cache to do two threads of a particular algo, the autoconfiguration limit will still be two threads.  Again it's a hint not an enforcement, and has nothing to do with runtime once the definitions have been generated and saved.

Intensity is simply how many work subthreads to run under a single upper management thread.  Normally 1:1 but you can do 2 threads per core for some smaller algos (cn-pico) for some gains.  This is different than what intensity means for GPUs, which is more like work batch size.  Never needs to be used unless the autoconfigurator already did, thus the lack of docs on how to use it.

Affinity depends on your system.  In general it's the core number beginning with zero, except where `-1` means automatic.  So if you have 8 thread cpu then you can use affinity 0-7, but with hyperthreading half of them will be the fake-cores, but which ones depend on the OS (Linux generally interleaves them so that evens are real and odds are fake, Windows does whatever it wants but usually all reals and then all fakes not interleaved).  But this CPU affinity idea is universal and not special to this miner, so google "what is cpu affinity", the knowledge of that is outside the scope of documentation here (or we should also document how electricity works? at some level).

Everything else about how thread decisions are made depend on the algo, and you need to know each algo's requirements to predict what autconfiguration will do.  In general for cryptonights divide the cache size by scratchpad size for max threads, and then if that is somehow larger than actual physical cores (not "threads") then reduce to physical core count.  So normal cryptonight is 2MB therefore to fully utilize a four core cpu it would need 8MB cache minimum, otherwise threads will be cut (a CPU core is pointless without cache to back it, for mining).  Other algos have other limitations which is again outside the scope of the CPU.md docs.

**Comment by crocket** [comment]
The documentation still doesn't explain what a CPU affinity number means.

Until I read https://github.com/xmrig/xmrig/issues/2084#issuecomment-774500529, I thought CPU affinity number was some black magic.

I thought `[-1, -1, -,1 -1]` instructed xmrig to use the first 4 CPU threads.

**Comment by Spudz76** [comment]
Nah, cpu affinity is always core number from 0, that's an industry standard.  Equal to the cpu index from sysfs (`ls -d /sys/devices/system/cpu/cpu*`) which makes so much sense it seems obvious.  Only other option is raw affinity-mask bitfield but that doesn't make sense unless specifying multiple cores into groups (which is not useful for a miner app).  Stuff like MySQL uses the raw bitmask for (optional) affinities as that type of task can be "fenced" to a certain subset of multiple cores.

So then `-1` is the only mysterious setting but that's also fairly standard for "don't care" or "auto" wherever literal null or strings are invalid.

**Comment by crocket** [comment]
Anyway, I think things I mentioned are better documented because new miners haven't used any application that deals with CPU affinity.

**Comment by SChernykh** [comment]
-1 means thread affinity is not set by XMRig at all, so it's up to OS which core to use for this thread.

**Comment by Jauza24** [comment]
i still can't decrease my cpu threads, 😓h..hh im so tired, I've been 6 more hours just for trying to running it

![IMG_20210530_154845](https://user-images.githubusercontent.com/44543268/120098226-26de0500-c124-11eb-8c91-e5f33d9a0e8c.jpg)
as you can see I stopped the program, because if not it'll freeze and shut down the whole programs. I've tried to use the config but it still doesn't work, now I've no idea for what can make the program run properly.

sh#t

**Comment by SChernykh** [comment]
https://xmrig.com/docs/miner/command-line-options
```
--randomx-init=N thread count to initialize RandomX dataset
--threads=N number of CPU threads. Proper CPU affinity required for some optimizations.
```

**Comment by Spudz76** [comment]
Note: you have to delete all algo-defs from the cpu section of the config.json for initial configuration mode hints like `--threads` to work... or it doesn't autoconfigure thus doesn't need your thread hints.  It isn't an override, it's a hint...
