### ISSUE TITLE
Xmrig termux crash

### ISSUE THREAD

**Issue by arunAK47AK** [xmrig/xmrig#2226]
My cpu cortex a-53 all settings fine , start mining termux closed

**Comment by arunAK47AK** [comment]
Give any ideas for mining with Android mobile

**Comment by Spudz76** [comment]
Use cross-compile toolchain from Android SDK (matching your device Android revision) to build executable on normal Intel/AMD computer targeted for aarch64

Copy executable with ADB, or use Android SDK to build APK file, crossload.

**Comment by snipeTR** [comment]
It is an extremely difficult affair to work on every android phone. and if you don't have tens of thousands of phones, you won't get any significant value.

**Comment by arunAK47AK** [comment]
Ohh yes 🙂 in xmrfast pool shows my phone  has power 40 to 50  h/s 🙄🤔 few years take minimum withdraw

**Comment by Spudz76** [comment]
It might be good enough at other algos, CN-Lite or something.

**Comment by afl45** [comment]
hi, i join this chat because i want learn xmrig on my honor 10 lite phone android, i know don't get a reward for a very long time but it's just for educational purposes. i lunch ./xmrig on termux but after 30 seconds, termux crash. can i have help on my problem ? i can't understand the bug report related to this incident.
[dumpstate_log.txt](https://github.com/xmrig/xmrig/files/11080644/dumpstate_log.txt)
