### ISSUE TITLE
Can't use xmrig with  Cygwin

### ISSUE THREAD

**Issue by tradesmart844** [xmrig/xmrig#2268]
I tried Linux xmrig binary as well build from source in cygwin on windows 10 machine. Unable start xmrig in cygwin. Has anyone tried this & got success?

**Comment by Spudz76** [comment]
I believe msys64 is the only non-MSVC windows compiler supported, and even then it barely ever works.

I have never gotten cygwin64 to build successfully.  Nor msys64 actually.  I just stick to the free MSVS2019 Build Tools since that always works fine.

Cygwin is not for straight up running Linux apps, it's for compiling vanilla Linux app code on Windows without making it MSVC aware - but when something uses the memory functions for hugepages it's unsupported (unless it's partially windows aware... and cygwin gcc doesn't set any windows-related compiler defines to act as if it's Linux, by default).  Have not figured out proper workarounds.

**Comment by tradesmart844** [comment]
Yes you correct, while building it on cygwin64, cmake was complaining about that.
