### ISSUE TITLE
Considered as potentially-unwanted application/software (PUAS)

### ISSUE THREAD

**Issue by ethindp** [xmrig/xmrig#2285]
I just tried using this today and malwarebytes immediately flagged/erased the executable. It considers it RiskWare.BitCoinMiner. I've read positive reviews but I feel that asking the developers directly about the security of the application and whether its malicious or not was also a good idea. I'd look through the code for myself but I don't have enough knowledge to audit this with the proper degree of certainty. So, is there a reason for this, and is it safe to mark as an exclusion? (According to research I've read there have been cases of xmrig being used in malware payloads, which may be the reason for it being flagged.)

**Comment by Lonnegan** [comment]
Malwarebytes has detected xmrig as a coin miner? Well, xmrig IS a coin miner?!

**Comment by ethindp** [comment]
That has to be the most unhelpful response ever.

**Comment by SChernykh** [comment]
If you downloaded from https://github.com/xmrig/xmrig/releases and SHA256 sums match/PGP signature checks out then it's not malicious. Antiviruses always flag all miners.

**Comment by ethindp** [comment]
I did. Had to allow it through. From my research it seems like people make modifications to XMRig in malicious code so you'd think the AV software would only flag those particular forks but maybe they can't tell so they just flag all the miners instead?

**Comment by SChernykh** [comment]
AV flag all versions of xmrig, even the ones you compile yourself. This is just how it is.

**Comment by Lonnegan** [comment]
The reason why miners got flagged is, that some bad boys used the hardware of innocent people for mining. For those people a coin miner is an unwanted application but since the AV cannot distinguish whether you installed the miner intentionally or whether it was pushed to you without your knowledge, most AV programs mark a miner as a "potentially unwanted application". When it detects a coin miner, it's ok. It IS a coin miner! It becomes dangerous if anything else is discovered.
