### ISSUE TITLE
api /1/threads not work

### ISSUE THREAD

**Issue by PandaUncle** [xmrig/xmrig#2318]
get /1/threads, response is { "status": 404, "error": "Not Found" }
version: 6.12.1

**Comment by Spudz76** [comment]
I noticed this also, apparently that endpoint was dropped sometime.  Sucks because it was the only way to get `PCI Location => GPU index` mappings... to know which one was really which...

The only valid endpoint now for status information is `/1/summary`

I do not know when it was changed, but I do know my old monitor script used `/1/threads` and it didn't work when I went to use it again.  And it used PCI location as the GPU identifier, not indices, so the summary doesn't work for me at all.

**Comment by xmrig** [comment]
#1541

**Comment by Spudz76** [comment]
Oh dang, completely missed the existence of `/2/backends`, thanks for the pointer!
