### ISSUE TITLE
[SUGGESTION] Idle time percent

### ISSUE THREAD

**Issue by XfedeX** [xmrig/xmrig#2465]
**What do you mean?**
You should add a setting that sets the idle time in percent, similar to [crypto-webminer](https://www.crypto-webminer.com/integrate.html?).
E.G. : If it is set to 10 then the miner will "sleep" for 1ms and then work for 9ms.
This would allow to limit CPU usage and using all cores, thus avoiding cores overheating.

**Comment by Spudz76** [comment]
There is a `bsleep` for the CUDA backend and I agree it would be nice to have similar in the OpenCL backend (which might as well also then be adapted into the CPU backend).  OpenCL really chokes out GUI when mining even with lowered intensities due to no "breathing room" sleep setting.  I can see how a bsleep for CPU would help in some setups.
