### ISSUE TITLE
No Status Via S key (in beta)

### ISSUE THREAD

**Issue by wwinter86** [xmrig/xmrig#2571]
Normally you can press S key in command line to see results but you can not in the current beta version.

**Comment by Spudz76** [comment]
As in the other issue, the `beta` branch is antique and hasn't been remerged in a while (it is at v6.2.0-beta while master is v6.15.0)

It probably didn't even have 'S' command yet.  Among lots of other features and changes... so this falls under expected behavior but maybe the beta branch shouldn't be a trap / at least be equal to current dev if there isn't a beta.

Currently `dev` branch is functionally like the abandoned `beta` branch, `evo` is ahead of that like experimental or large changes in progress and was also abandoned until recently.  When `evo` has something nearly releasable but needs more widely tested it might roll into the `beta` branch.  I tend to run `dev` normally, as if it were `beta`.
