### ISSUE TITLE
Difference between XMRig-Cuda and XMRig-NVIDIA

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [xmrig/xmrig#2592]
What exactly is [XMRig-Nvidia](https://github.com/xmrig/xmrig-nvidia), and how is it different from [XMRig-Cuda](https://github.com/xmrig/xmrig-cuda)?

**Comment by Spudz76** [comment]
xmrig-nvidia was a separate miner that is deprecated when xmrig-cuda became a plugin for regular xmrig.

**Comment by HiDe-Techno-Tips** [comment]
Is [XMRig-AMD](https://github.com/xmrig/xmrig-amd) deprecated too?

**Comment by Spudz76** [comment]
Yes.  Only exist for posterity.  Always check dates and freshness.

OpenCL (AMD) is included in main xmrig (no plugin, no separate plugin project)

Technically CUDA was also included into the main app for a while, but CUDA has weird compilation requirements so it was split to a plugin library so the main app can be compiled with today's compilers and CUDA can be compiled with gcc-5 or whatever terrible garbage it requires per CUDA Toolkit version (always changing).

**Comment by HiDe-Techno-Tips** [comment]
Even main XMRig app has some weird requirement for compiling. I had to download sources for XMRig as well as XMRig Deps to compile in MSVCC. If XMRig Deps is required for compiling main XMRig, why are they in two different repos?

**Comment by Spudz76** [comment]
Because the Windows deps are all binaries and would really twerk the commit history of a code repo (cause rebase and such to take a long time for binary comparisons).  Having it split external keeps the main repo clean of binary garbage.

Linux deps are included in the main repo in source (text) form and can be compiled easily, where getting them to compile under MSVC is a real pain, so the work has been done for us in the xmrig-deps repo.
