### ISSUE TITLE
HTTP API config

### ISSUE THREAD

**Issue by vpts1202** [xmrig/xmrig#2602]
My query is for HTTP API config
How to use it?
What should I add(http:// ?) as the “new worker”?
How(in plain language, i.e. click/right click/double click/etc.)  to execute “executing API calls”?
I have configured as below but it does not seems workable
{
    "api": {
        "worker-id": "0.0.0.0"
    },
    "http": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 0,
        "access-token": null,
        "restricted": false
    },

Thanks

**Comment by Spudz76** [comment]
Examples at the bottom of [API documentation](https://github.com/xmrig/xmrig/blob/master/doc/API.md)

Not sure if it works without setting an `access-token`...

**Comment by vpts1202** [comment]
> 
> 
> Examples at the bottom of [API documentation](https://github.com/xmrig/xmrig/blob/master/doc/API.md)
> 
> Not sure if it works without setting an `access-token`...

Many thanks for prompt and useful feedback.
1)	How to set  access-token? Or its okay to place some kind of password like “xYz2mj”?
2)	Should be config looks like below?

"api": {
	"id": null,
	"worker-id": null,
},
"http": {
	"enabled": true,
	"host": "0.0.0.0",
	"port": 0,
	"access-token": [?],
	"restricted": false
}

Once again thank you for your kind assistance. Look forward for your feedback for in above.

**Comment by Spudz76** [comment]
Yes access-token is simply shared secret string, long and random is good.

If you use workers.xmrig.info site it is a locally-running API client.

**Comment by vpts1202** [comment]
> 
> 
> Yes access-token is simply shared secret string, long and random is good.
> 
> If you use workers.xmrig.info site it is a locally-running API client.

1)	What does it mean “a locally-running API client” in your context?
2)	Port should be chosen in the range of open ports of website workers.xmrig.info?

Sorry for annoying you, I just want to make sure all details since rule “The devil is in details” is always in place))
Thank you!

**Comment by Spudz76** [comment]
workers.xmrig.info does not receive any information about your miners.  The browser runs a fully local private monitoring -- it does not cause the web server to connect to your miners from "outside", your browser itself becomes an API client app.  All your miners are set in a cookie which is not sent to the outside Internet.  Therefore it can't be a security hole, none of your information leaves your browser.  Usually a web site sends information to the server so I mentioned "locally-running" meaning it is a javascript app that does all its work inside your LAN.

You don't need any firewall openings for workers.xmrig.info since the browser itself is doing the connections to your miners (all inside LAN realm).
