### ISSUE TITLE
database de-initilization for saving memory during paused mining after a period of time

### ISSUE THREAD

**Issue by JacksonChen666** [xmrig/xmrig#3072]
# the problem
when xmrig loads the randomx database, it uses quite a lot of memory (2GB+ memory).
sometimes, when not mining for long periods of time (like paused because running on battery for a long time now, like 30 minutes), it's not being used, and pretty much becomes wasted RAM that could be used for the rest of the system.

# the proposed solution
freeing up that used RAM (of randomx database, which is pretty much wasted RAM at that moment) could be helpful minimizing the use of RAM by the program when it isn't actively using it.
how about, a configuration option to say after how many seconds/minutes of paused mining should xmrig unload the randomx database.

# how it is applicable
well, on systems that gets used and not used for a long period of time and doesn't have as much RAM necessary for everything, RAM can become a pretty limited resource. or even more limited

# alternative solutions
- use `--light-mode`. but i'm pretty sure that's pretty detrimental to the hash rate.
- depending on the system to swap the memory instead of bothering with this issue at all (is it a good idea?)

**Comment by Spudz76** [comment]
Since pausing stays connected and the state machine requires active dataset (algo "ready") to be connected, this would be extra complicated to implement.

Most users especially on windows would rather the hugepages stay allocated since releasing them could mean you never get them back until a reboot.  Otherwise they would quit and relaunch later (rather than pause, which again doesn't even disconnect).

I want it to disconnect while paused myself, so the autodiff doesn't fall to the minimum and then spam the server upon resume.  Even that seemed difficult to implement, the dataset is even deeper than that.

**Comment by JacksonChen666** [comment]
@Spudz76 thanks for the explanation.

will be closing. re-open if the plan could be feasible.
