### ISSUE TITLE
NOT AN ISSUE ! how to automatically assign the ip address as worker name..? Is it possible?

### ISSUE THREAD

**Issue by Gill1000** [xmrig/xmrig#365]
I was wondering ,can the worker name automatically assign to the ip address as it worker name.. @xmrig .....?

**Comment by xmrig** [comment]
You can use bat/cmd file instead of config file and use some solution from here https://stackoverflow.com/questions/5898763/how-do-i-get-the-ip-address-into-a-batch-file-variable

Also how set worker name, depends of pool, not all support this feature and not all allow use dot in worker name.
Thank you.

**Comment by sv0** [comment]
You can try following approach if you use Linux/FreeBSD:
 
    IP=`dig +short myip.opendns.com @resolver1.opendns.com`
    xmrig -o stratum+tcp://pool.host.com:port  -u MoneroWallet -p $IP

**Comment by djdomi** [comment]
@sv0 
I think he mentoid how to get the Local IP from the LAN-Worker

**Comment by enwillyado** [comment]
@Gill1000 you can use the https://github.com/enwillyado/xmrig/releases that permit to include special meta-data in for the user name.
