### ISSUE TITLE
--nicehash What is the flag?

### ISSUE THREAD

**Issue by RemezW** [xmrig/xmrig#37]
Hello! What is the flag for? 
What is the difference between:

> xmrig.exe -o stratum+tcp://cryptonight.eu.nicehash.com:3355 -u WALLET.1 -p x -k

and

> xmrig.exe -o stratum+tcp://cryptonight.eu.nicehash.com:3355 -u WALLET.1 -p x -k **--nicehash**

Do I need to use this flag if I use nicehash? Thank you.

**Comment by xmrig** [comment]
In that case no difference, because it detected from pool url (nicehash.com), explicitly specify `--nicehash` need only if detection by url may failed, for example connect by IP address or stratum proxy.

Nicehash have little difference in protocol, that need special handle, otherwise all shares will be invalid.
Also nicehash does not support `-k` option.
Thank you.
