### ISSUE TITLE
Add Mod question/request

### ISSUE THREAD

**Issue by Zelecktor** [xmrig/xmrig#411]
Something interesting is that i found a mod to manage and monitoring miners/workers with an easy configuration server.

See this proyect
https://github.com/Bendr0id/xmrigCC

The only bad is that it uses two .exes files and have unnesesary addons. I would like have separates things. The mining software for one side (just only the original xmrig.exe) and the server exe (or file for linux) in another side.

**Comment by Zelecktor** [comment]
To explain in simple words, it has 3 files, daemon (client), miner and server.
Server is independant. (its ok)

The miner is dependant of daemon (client), without daemon, the miner doesnt run. In summary both files (two .exe files on windows) must be together. On this case daemon is responsible to interact (send/receive) server orders.
My question is if it is possible to make only one file (client+miner) that can interact with the server but also mine. Just imagine xmrig running and monitoring with the CC server.

**Comment by MarQuisKnox** [comment]
Better to ask in the XMRigCC project, since it is a fork & not directly compatible w/ the original XMRig:  https://github.com/Bendr0id/xmrigCC/issues/new

Also, maybe there's a good reason why this design was implemented. Simply ask on the XMRigCC issue tracker. @Bendr0id normally responds promptly.
