### ISSUE TITLE
new plugin version 2.5.x for Freenas available

### ISSUE THREAD

**Issue by adieball** [xmrig/xmrig#490]
Hi.

is there (or will be) a new plugin version (min. 2.5.x) available for freeness soon?
The current 2.4.5 will stop working on the 6th of April ....

thanks

**Comment by xmrig** [comment]
You should contact with person who created the plugin or build miner from source.
Thank you.

**Comment by DrStein99** [comment]
I was curious about that myself.  It's like freeNAS has it's own operating system with it's own version of docker (called the plugin or JAIL).  I wanted to simply install centos or ubuntu and have FREENAS be front end, so I can simply load whatever I wanted - instead of loading a whole operating system to run as a virtual machine, under the already running operating system hosting the FREENAS.

Probably a good time to start learning how to use docker with FREENAS at this point (if it is possible)....

**Comment by estredgx** [comment]
Hello, could someone help me set up the xmrig on ubuntu? my problem is that I am mining with only 5 cpu and I have rented a digital ocean vps of 16cpu and I can not confirm it

**Comment by josh4trunks** [comment]
@adieball
The FreeNAS plugin for XMRig version 2.5.2 is now available from the FreeNAS repo
