### ISSUE TITLE
How to make sure both processors are being used

### ISSUE THREAD

**Issue by mirrormirage0** [xmrig/xmrig#491]
I have an HP WX8600 workstation with 2 XEON X5450 processors running at 3.40 GHz
When I start xmrig using Awesome miner, I see that it uses **8 Threads** 
I am getting a hash rate of **172 H/s** for Cryptonight Algorithm.
There are 2 Processors in the workstation, and each XEON X5450 has 12 MB cache

One issue I find is that the processor does not support AES.
1) Is this the reason why the hashrate is low?
2) How do I ensure that both processors are being used?

**Comment by NmxMilk** [comment]
These are quad cores. So max is 8 threads.
Intel's site indicates 3.00 GHz and not 3.40 GHz!
Try with just 1 thread, I guess that would give about 30 H/S (since no AES).
You can in this way evaluate the max H/S with 8 threads.
Don't be astonished if you get less. Maybe best perf you get will be with 6 or 7 threads.

**Comment by xmrig** [comment]
If this issue still actual, please check v2.99.2-beta release #1077.
Thank you.
