### ISSUE TITLE
Why does xmrig don't support BTV?

### ISSUE THREAD

**Issue by Allin1920** [xmrig/xmrig#650]
Why does xmrig don't support BTV?
Http://www.uupool.cn/course/btv
Pool: btv.uupool.cn:9501
-u 1661dUzs2uD4q4cFhALPZTLXxHQ8eRDkq1
But https://github.com/bitcoinvote/cpuminer-multi support.
Minerd -a cryptonight -o stratum+tcp://btv.uupool.cn:9501 -u 1661dUzs2uD4q4cFhALPZTLXxHQ8eRDkq1.worker1 -p x
I can't understand.

Cpuminer-multi is sending data at {"Id": 2, "method": "mining.authorize", "params": "[1661dUzs2uD4q4cFhALPZTLXxHQ8eRDkq1", "X"].

**Comment by xmrig** [comment]
This coin use stratum protocol which not compatible with all other cryptonight coins, `mining.authorize` is invalid method for cryptonight stratum protocol.

https://github.com/bitcoinvote/cpuminer-multi Of course it support BTV because if forked by BTV team.

Also http://www.uupool.cn/course/btv looks down from my location.

**Comment by Allin1920** [comment]
You mean that xmrig can't support BTV?
So you can only use cpuminer-multi?

**Comment by Allin1920** [comment]
So we can only use cpuminer-multi?
