### ISSUE TITLE
config.json new parameters meaining explanation is absent

### ISSUE THREAD

**Issue by lisergey** [xmrig/xmrig#716]
It would be great to update Wiki about all new wonderfull params of config.json, that were added recently.
E.g. `watch: false` or `user-agent: null` - what is their meaning and what they change in behavior.

I've been searching in issues and in wiki - nothing found. I'm no expert to understand from reading the code. Thank you in advance, @xmrig.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/issues/119 same as watch feature in proxy, but this feature disabled in miner because reaction to config change not implemented, proxy and miner share same code base.

`user-agent` allow override default miner user agent from `XMRig/<version> ...` to something else.
