### ISSUE TITLE
How to build and run test ?

### ISSUE THREAD

**Issue by kalagane** [xmrig/xmrig#75]
Hello, I checkout the sources and try to build and launch test.... but I failed.
Someone can give me the command lines please?

**Comment by xmrig** [comment]
test abandoned since version 1.0.0, it no work now.

There was 2 kind of test cryptonight algo test, now it happen on every miner run, test values https://github.com/xmrig/xmrig/blob/master/src/crypto/CryptoNight_test.h

And auto-configuration test, there no big changes since 0.8, still lazy to fix it.
Thank you.

**Comment by kalagane** [comment]
ok, thanks for the answers
