### ISSUE TITLE
240 compiling errors

### ISSUE THREAD

**Issue by Neoxyne** [xmrig/xmrig#762]
why don't you just upload the vs source ...
i generated the project with cmake then included the missing libraries,
and when i was trying to compile i got 240 errors

**Comment by reeyon** [comment]
I have problem after compiling in dev branch, the xmrig cannot run due to missing dlls.
![image](https://user-images.githubusercontent.com/3666089/45992480-bce04880-c0bc-11e8-8e1b-70fbb9ae3a52.png)
![image](https://user-images.githubusercontent.com/3666089/45992481-bf42a280-c0bc-11e8-9ef9-6e3a974c54a1.png)

**Comment by xmrig** [comment]
Follow documentation https://github.com/xmrig/xmrig/wiki/Windows-Build and use [xmrig-deps](https://github.com/xmrig/xmrig-deps/releases) if you for some reason don't like use prebuilt libraries, you should use static libraries to aboid such issues.
Thank you.

**Comment by reeyon** [comment]
downloaded the updated xmrig-deps fixed the issue. Thanks.

**Comment by reeyon** [comment]
cmake with the updated xmrig-deps fixed the issue, thanks.
