### ISSUE TITLE
Update on new algorithm in October 18th

### ISSUE THREAD

**Issue by ttsite** [xmrig/xmrig#763]
Can the new algorithm version be automatically updated in order to prevent the subsequent updating algorithm from being manually updated? thanks.

**Comment by xmrig** [comment]
All information here #753
Thank you.

**Comment by ttsite** [comment]
I want to say whether automatic updates can be implemented in releases after October 18, that is, every time a new version is available, it can be automatically updated to a new version. This eliminates the trouble of manually updating every major version. Thank you.

**Comment by xmrig** [comment]
Automatic update have 2 issues:
* It potential backdoor to all miners, it can be compromised just because it can be.
* It make antiviruses much more anger to miners.

I understand your concept, but security of automatic update is much more important from my point of view. Anyway I will leave this issue open to reminder.
Thank you.

**Comment by snipeTR** [comment]
Yeah, that makes sense. like a config.xmrig.com service. A service such as update.xmrig.com can be made.

**Comment by lukacci** [comment]
> An auto updater software for xmrig miners.
> Download it from https://github.com/lukacci/xmrig_updater.
