### ISSUE TITLE
Windows defender says xmrig.exe has a trojan

### ISSUE THREAD

**Issue by trashhalo** [xmrig/xmrig#85]
specifically Trojan:Win32/Tilken.B!cl

do you know whats up with that?

**Comment by xmrig** [comment]
What version? If you download it from github nothing worry about. It periodically happens to all miners without exception, some people put it to botnets, it makes AV companies angry.

Also Windows Defender very funny, some time ago it claims xmrig and xmr-stak-cpu as trojan with exactly same name. Also claim 32bit proxy (not a miner, but based on same codebase) version as a trojan only because it contains word Monero in description.

**Comment by theycallmepepper** [comment]
Flagged as vigorf.a - xmrig-2.3.1-msvc-win64.zip

**Comment by maxkaplan** [comment]
Just a heads up - this also popped up for me: 
![image](https://user-images.githubusercontent.com/200634/34507880-2b96062e-efef-11e7-9415-063c01cd0b26.png)

**Comment by versteckt** [comment]
Flagged as "Trojan:Win32/Bluteal!rfn" for me.

And yes, this is because so many trojans use xmrig in their payload to stealth mine stuff like Monero. Just "allow" it in your AV so that it stop deleting your executable like it was for me, and you should be OK. :-)

**Comment by minorminer** [comment]
Windows is blocking, and calling "Severe Threat" this script:  Trojan:Script/Wacatac.B!ml which came with the latest XMRig download (xmrig-6.15.1-gcc-win64) this morning. Any word on whether or not this is a concern or just Windows being over protective? Hesitant to make a move.
