### ISSUE TITLE
New algo for Graft, CN Waltz. Support?

### ISSUE THREAD

**Issue by pikomule** [xmrig/xmrig#923]
CryptoNight Waltz custom POW is ready for testing:

Seeds:
54.208.86.27:28880
54.144.192.6:28880
35.175.164.180:28880
Recent HF Height: 261100

https://github.com/graft-project/GraftNetwork/tree/test/cn_waltz_test

**Comment by xmrig** [comment]
Just another variation of changing iteration count, the third such change in the last few weeks. Little boring.
Thank you.

**Comment by xmrig** [comment]
@zelerius @graft-project please explain current situation, looks like both coins will use same algorithm (cn/2 with 393216 iterations) https://github.com/fireice-uk/xmr-stak/pull/2196

So thank you for suggested name for the algorithm, but little name conflict here.

**Comment by zelerius** [comment]
This is very rare or just a coincidence...

We have done several tests months ago and we want to change the iterations in the next hard fork in order to avoid merged mining. We have everything ready, for that reason, we have made several PR for example 
https://github.com/fireice-uk/xmr-stak/pull/2196 and https://github.com/MoneroOcean/node-cryptonight-hashing/pull/21

Our intention is calling this little variation as **cryptonight_zlx** but this situation changes everything... we have identified several pools where people mine Graft and Zelerius at the same time, for example, this one https://webgrft.semipool.com/#/blockauxs This is exactly what we want to avoid.

**Comment by Patrickdurbin** [comment]
Yes its on the testnet but just the other day on the Graft mining channel we were discussing a different algo.  So graft dev's need to chime in.

**Comment by nilhcraiv** [comment]
Ok, thank you. Then we are waiting for a response from Graft dev's. If they use this number of iterations we will use other custom variation of CN.

**Comment by EDDragonWolf** [comment]
@xmrig 
We have learned about Zelerius and their changes a day ago and found the latter quite surprising. 

Waltz landed in our main repository 7 days ago (https://github.com/graft-project/GraftNetwork/pull/216). The current variant was based on CNv8, is not final, we're still weighing our options for CNv8, CNv0, Heavy, etc.

We'd call it a new hashing algorithm but rather a CryptoNight tweak. It was named Waltz because this tweak used 3/4 iteration of original CryptoNight and waltz dance has 3/4 time signature.

**Comment by nilhcraiv** [comment]
Sorry but we have done private test months ago and our changes were published 7 days ago on github, as you can see here https://github.com/zelerius/Zelerius-Network/commit/8e3527fac13319e90559076a34283e6df0f7c33d For that reason we have the code for xmr-stak and node-cryptonight-hashing as Zelerius said in his last comment. Our intention is to make a hard fork with our custom variation of CNv8 but if Graft network wants the same variation of this algorithm, then we will make a different variation of CNv8. Please tell us your intention. **Does Graft network want to include our variation?**

**Comment by Patrickdurbin** [comment]
![new bitmap image](https://user-images.githubusercontent.com/36722911/52235019-9612f980-2888-11e9-93b9-b62868c410b3.png)

**Comment by nilhcraiv** [comment]
Please tell us our intention

**Comment by Patrickdurbin** [comment]
Honestly I planned on using a 3/4 iteration change but I felt that your coin would be merge mined with mine and I didn't want to devalue it since obviously my coin would be the parent coin.  So I'm trying to figure out which one of you guys need the algo more then me since you cant merge mine all 3 of us together.

**Comment by anartz** [comment]
be honest man of GRAFT coin, stop this foolishness...quite sad this kind of comments from a "serious" dev...LMAO

**Comment by fireice-uk** [comment]
> Just another variation of changing iteration count, the third such change in the last few weeks. Little boring.

@xmrig I get why they do it, just **try** to modify something here so that it is supported both on SSE2 and ARMs https://github.com/monero-project/monero/blob/master/src/crypto/slow-hash.c I tend to swap the code out altogether for my jobs :)

**Comment by nilhcraiv** [comment]
@fireice-uk Yes it is quite complicated ;)

**Comment by Patrickdurbin** [comment]
lol Im not a graft dev

**Comment by nilhcraiv** [comment]
I’m not fighting over iteration change I’m just waiting for a response from Graft dev’s for that reason we want to give the change to them if they want use it. I’m waiting for a simple response from them

**Comment by psychocrypt** [comment]
@xmrig my answer to the new hobby to change the number of iteration is [this WIP PR](https://github.com/fireice-uk/xmr-stak/pull/2209). It will allow the use to mine a modification of an original POW algorithm with modified iteration without the need to update the miner.
`cn_half` will be `cryptonight_monero_v8:0x00040000:0x00200000:0x1FFFF0:`

**Comment by xmrig** [comment]
@psychocrypt It's crazy I think I will not add same thing, but if it not break performance who knows. Also take look to this code https://github.com/xmrig/xmrig/blob/master/src/workers/CpuThread.cpp#L111 introduced via #905 It allow change ASM code on fly too.
Thank you.

**Comment by jagerman** [comment]
@nilhcraiv - I understand why you wouldn't want merge mining, but wouldn't it be simpler to just modify the blockchain to not accept merge-mined blocks?

**Comment by jagerman** [comment]
> It was named Waltz because this tweak used 3/4 iteration of original CryptoNight and waltz dance has 3/4 time signature.

Given that it actually cuts from 0x80000 to 0x60000 iterations, I feel a 6/8 time signature is more appropriate.  So maybe it should be called CN-double-jig?  Or CN-Hallelujah?

**Comment by nilhcraiv** [comment]
The initial idea was to temporarily avoid Nicehash. The merged mined represents a low percentage, in the future, we will also eliminate it.

Finally, we are going to fork over the next few weeks with 0x60000 iterations. For now, no currency is using it, then we have called it ZLS. Honestly, the name does not matter to us but we will call it ZLS for this reason. It is a minimal change, fight for the name does not make sense :) Thank you

**Comment by xmrig** [comment]
I close this issue both Zelerius variant and Graft/Waltz (the new one) is added to dev branch.
Thank you.
