### ISSUE TITLE
Will heavyx (x-cash) be supported?

### ISSUE THREAD

**Issue by pboguk** [xmrig/xmrig#940]
Hi,

5 days ago x-cash forked to heavyx algo? Do you plan to support it?

Thanks!

**Comment by xmrig** [comment]
It's not high priority task, I can't track every small coin and was know about the fork just right after it happen, so x-cash like many others want live in own small ecosystem.
Thank you.

**Comment by zachhildreth** [comment]
Hi xmrig,
This is Zach, the CTO of X-CASH

I was wondering if you will be able to add our Cryptonight HeavyX algo into a release of your mining software?

It should not be too difficult to add since it is basically the same thing as cn/half with 4x the loops basically.

Daemon: https://github.com/X-CASH-official/X-CASH/releases/tag/1.5.0

You can reach us through the Discord community if any further information required, or on github:
https://discord.gg/sr5G3ch

Please let us know if you need anything,
Thanks,
Zach

**Comment by xmrig** [comment]
This algorithm added in dev branch with name `cn/double`.
Thank you.

**Comment by xmrig** [comment]
v2.14.0 released https://github.com/xmrig/xmrig/releases/tag/v2.14.0
